add_library(fake_j2534 SHARED fake_driver.cpp)
target_include_directories(fake_j2534 PRIVATE ../proxy/include)
set_target_properties(fake_j2534 PROPERTIES PREFIX "" OUTPUT_NAME "fake_j2534")

if(WIN32)
    target_sources(fake_j2534 PRIVATE fake_j2534.def)
endif()
if(MINGW)
    target_link_options(fake_j2534 PRIVATE -Wl,--kill-at)
endif()
if(NOT WIN32)
    find_package(Threads REQUIRED)
    target_link_libraries(fake_j2534 PRIVATE Threads::Threads)
endif()
